CREATE TABLE PACIENTE(	
    PAC_ID NUMBER GENERATED BY DEFAULT AS IDENTITY, 
	NOME VARCHAR2(150 BYTE), 
	NASCIMENTO DATE, 
	CONVENIO VARCHAR2(100 BYTE), 
	PRIMARY KEY ("PAC_ID")
);

ALTER table PACIENTE add cpf varchar(11);

CREATE TABLE FUNCIONARIO(
    FUNC_ID number GENERATED by DEFAULT as IDENTITY,
    nome varchar(100),
    cargo varchar(100),
    primary key(FUNC_ID)
);

create table ATENDIMENTO(
    ATEND_ID number GENERATED by DEFAULT as IDENTITY,
    chegada date,
    saida date,
    desfecho varchar(15),
    PAC_ID_FK number,
    primary key(ATEND_ID)
    foreign key(PAC_ID_FK) references PACIENTE(PAC_ID),
);

create table TRIAGEM(
    TRIAGEM_ID number GENERATED BY DEFAULT as IDENTITY,
    data date,
    peso number,
    altura number(3, 2),
    batimento number,
    pressao varchar(10),
    temperatura number(3, 1),
    sintomas varchar(200),
    ATEND_ID_FK number,
    FUNC_ID_FK number,
    PRIMARY KEY(TRIAGEM_ID),
    foreign KEY(ATEND_ID_FK) references ATENDIMENTO(ATEND_ID),
    foreign key(FUNC_ID_FK) references FUNCIONARIO(FUNC_ID)
);

CREATE TABLE PRONTUARIO(
    PRONT_ID number GENERATED by DEFAULT AS IDENTITY,
    data date,
    descricao varchar(200),
    observacao varchar(200),
    ATEND_ID_FK number,
    FUNC_ID_FK number,
    PRIMARY KEY(PRONT_ID),
    foreign KEY(ATEND_ID_FK) references ATENDIMENTO(ATEND_ID),
    foreign key(FUNC_ID_FK) references FUNCIONARIO(FUNC_ID)
);
