CREATE TABLE "PACIENTE" 
   (	"PAC_ID" NUMBER GENERATED BY DEFAULT AS IDENTITY, 
	"NOME" VARCHAR2(150 BYTE), 
	"NASCIMENTO" DATE, 
	"CONVENIO" VARCHAR2(100 BYTE), 
	 PRIMARY KEY ("PAC_ID"))
insert into paciente(nome, nascimento, convenio) 
     values('Henrique Dias', to_date('02/10/1980', 'DD/MM/YYYY'), 'Unimed');
insert into paciente(nome, nascimento, convenio) 
     values('Joana Novaes', to_date('15/05/1990', 'DD/MM/YYYY'), 'SUS');
insert into paciente(nome, nascimento, convenio) 
     values('Andreia Souza', to_date('10/12/2010', 'DD/MM/YYYY'), 'Care Plus');
insert into paciente(nome, nascimento, convenio) 
     values('Bruno Andrade', to_date('07/07/2000', 'DD/MM/YYYY'), 'Unimed');
     
select * from paciente;