create table filme(
    id number generated by default as identity,
    titulo varchar2(150),
    diretor varchar2(50),
    nota number(2,1),
    lancamento date,
    genero varchar2(50),
    duracao number,
    atores varchar2(300),
    primary key(id)
);