INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Maria Eduarda Castro', 'Porto Seguro', to_date('1967-10-24', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Liam Aragão', 'SUS', to_date('1983-05-10', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Mateus Cavalcanti', 'Prevent Sênior', to_date('1991-08-12', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Mateus Moreira', 'Unimed', to_date('1943-02-09', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Sarah Rodrigues', 'Prevent Sênior', to_date('2001-01-04', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Dr. Benjamim da Rocha', 'Sul América', to_date('2005-08-31', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Antony Novais', 'Bradesco Saúde', to_date('1987-06-26', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Amanda Cavalcante', 'Unimed', to_date('2008-01-10', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Dr. Felipe da Costa', 'Unimed', to_date('2015-07-04', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Clarice Siqueira', 'Particular', to_date('1997-04-27', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Isabelly Carvalho', 'Sul América', to_date('1944-01-03', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Benício Barbosa', 'Prevent Sênior', to_date('2000-04-26', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('João Felipe Macedo', 'Care Plus', to_date('1956-06-06', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Apollo Castro', 'Sul América', to_date('1996-03-23', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Sophia Rios', 'Unimed', to_date('1937-02-23', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Davi Rezende', 'Sul América', to_date('2009-04-19', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Emanuel Silveira', 'Care Plus', to_date('1980-10-01', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Helena Silveira', 'Porto Seguro', to_date('1948-02-21', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Julia Vasconcelos', 'Omint', to_date('1949-10-24', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Emanuelly Moreira', 'Unimed', to_date('1991-01-20', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Sr. Luan da Luz', 'Sul América', to_date('1998-01-31', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('João Guilherme Vargas', 'Porto Seguro', to_date('1994-07-09', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('João Jesus', 'Care Plus', to_date('1956-07-14', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Sr. Anthony Camargo', 'Sul América', to_date('1985-01-25', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Amanda Rocha', 'Particular', to_date('1984-05-28', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Daniel Sá', 'Prevent Sênior', to_date('2014-05-12', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Kevin Martins', 'Omint', to_date('1939-07-24', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Dra. Eloah Garcia', 'Sul América', to_date('1988-10-12', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Arthur Miguel Carvalho', 'Unimed', to_date('1948-03-11', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Luana Andrade', 'Sul América', to_date('1937-02-22', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Dra. Bárbara Moura', 'Care Plus', to_date('1941-03-23', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Isadora Pereira', 'Bradesco Saúde', to_date('2011-08-07', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Raquel Camargo', 'Bradesco Saúde', to_date('2013-12-12', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Dra. Sarah Pacheco', 'SUS', to_date('1949-06-02', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Ana Carolina Sampaio', 'Omint', to_date('1951-11-09', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Gabriel da Cruz', 'Omint', to_date('1946-01-08', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Heitor da Cruz', 'Particular', to_date('1950-01-14', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Ana Machado', 'SUS', to_date('1981-10-11', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Carolina Sousa', 'Unimed', to_date('2011-01-04', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Yago Albuquerque', 'SUS', to_date('1983-11-23', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Srta. Isabella Pires', 'Prevent Sênior', to_date('1946-04-14', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Clara Cassiano', 'Care Plus', to_date('2017-03-12', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Milena Brito', 'Care Plus', to_date('1962-11-05', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Yuri Viana', 'Sul América', to_date('1942-02-09', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Lívia Fernandes', 'Prevent Sênior', to_date('1945-10-26', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Jade da Costa', 'Porto Seguro', to_date('2010-09-12', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Marcos Vinicius Casa Grande', 'SUS', to_date('1993-05-11', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Marcela da Mata', 'Unimed', to_date('1948-06-25', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Ana Mendonça', 'Bradesco Saúde', to_date('1967-04-30', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Enzo Gabriel Lima', 'Particular', to_date('1967-03-26', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Vitor Cardoso', 'Unimed', to_date('1982-04-16', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Laís Vargas', 'Bradesco Saúde', to_date('1973-10-07', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Maria Vitória Cavalcante', 'Unimed', to_date('1946-04-04', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Sra. Maria Fernanda Casa Grande', 'Bradesco Saúde', to_date('1938-03-17', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Josué Vargas', 'Unimed', to_date('1969-12-19', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Luiza Mendonça', 'Particular', to_date('2001-12-28', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Julia da Mata', 'Porto Seguro', to_date('1966-07-05', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Caroline Machado', 'Sul América', to_date('2017-11-16', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Gabriel Dias', 'Omint', to_date('2000-01-01', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Alexandre Aragão', 'SUS', to_date('2012-04-03', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Rafael Moreira', 'Unimed', to_date('1943-07-31', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Sra. Pietra Pinto', 'Porto Seguro', to_date('1977-10-17', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Murilo Albuquerque', 'Porto Seguro', to_date('1954-09-23', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Maria Cecília Vasconcelos', 'SUS', to_date('1949-05-10', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Maysa Cassiano', 'Care Plus', to_date('1951-08-09', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Valentina Vargas', 'Porto Seguro', to_date('1999-04-07', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Sra. Rebeca Vasconcelos', 'SUS', to_date('2011-04-04', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Giovanna Montenegro', 'Porto Seguro', to_date('2006-08-21', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Lorena da Rocha', 'Prevent Sênior', to_date('1967-01-24', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Vitor Silveira', 'Particular', to_date('1942-07-10', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Otávio Sá', 'Porto Seguro', to_date('1972-04-18', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Isadora Camargo', 'Prevent Sênior', to_date('1958-05-04', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Murilo Pires', 'Bradesco Saúde', to_date('1965-11-26', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Antony Rocha', 'Sul América', to_date('1951-08-26', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Luara Mendonça', 'Sul América', to_date('1977-03-03', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Daniela Moura', 'Porto Seguro', to_date('1960-03-19', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Leonardo Novaes', 'Unimed', to_date('1997-07-01', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Amanda Rocha', 'SUS', to_date('1947-04-10', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Rafaela Moraes', 'Bradesco Saúde', to_date('1958-02-20', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Sra. Anna Liz da Rosa', 'Particular', to_date('1969-07-06', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Diego Pires', 'Sul América', to_date('2014-03-04', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Ana Cecília da Rosa', 'Sul América', to_date('2019-01-01', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Bárbara Casa Grande', 'Sul América', to_date('1983-05-07', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Lavínia Viana', 'Omint', to_date('2013-02-15', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Enzo Gabriel da Paz', 'Unimed', to_date('1975-05-18', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Yan da Cruz', 'Prevent Sênior', to_date('1994-02-24', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Sofia Silveira', 'Sul América', to_date('1996-09-20', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Sophia Montenegro', 'SUS', to_date('1955-07-02', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Sr. Theo Cavalcanti', 'Unimed', to_date('1980-12-31', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Sra. Maria Flor Brito', 'Prevent Sênior', to_date('1985-11-11', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Vitor Hugo Nunes', 'Prevent Sênior', to_date('1995-09-21', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Aurora Costela', 'Unimed', to_date('1963-06-19', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Milena Cirino', 'Particular', to_date('2017-06-24', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Guilherme Novais', 'Bradesco Saúde', to_date('2018-01-19', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Igor Nascimento', 'Care Plus', to_date('1978-09-15', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Antonella Lopes', 'SUS', to_date('1990-10-13', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Anthony Gabriel Farias', 'Prevent Sênior', to_date('1947-07-19', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Caroline Oliveira', 'Care Plus', to_date('1946-02-05', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Joana Ferreira', 'Care Plus', to_date('1938-06-25', 'YYYY-MM-DD'));
INSERT INTO PACIENTE(nome, convenio, nascimento) VALUES('Gael Henrique Montenegro', 'Omint', to_date('1980-04-29', 'YYYY-MM-DD'));
