create table tdspr_pessoa(
    id number generated by default as identity,
    nome varchar2(100),
    nascimento date,
    peso number,
    altura number(3, 2),
    sexo varchar2(20),
    primary key(id)
)