create table tdspr_cliente(
    id number generated by default as identity,
    nome varchar2(200),
    documento varchar2(50),
    email varchar2(100),
    telefone varchar2(50),
    primary key(id)
);

insert into tdspr_cliente(nome, documento, email, telefone) 
    values('Mario Lago', '384.827.980-56', 'mariolago@mar.br', 
    '(11) 9382-2930');

create table tdspr_venda(
    id number generated by default as identity,
    valor number(8, 2),
    data date,
    vendedor varchar2(50),
    fk_cliente number,
    primary key(id),
    foreign key(fk_cliente) references tdspr_cliente(id)
);

create table tdspr_itemvenda(
    produto varchar2(100),
    valor number(8, 2),
    quantidade number,
    fk_venda number,
    foreign key(fk_venda) references tdspr_venda(id)
);



