create table tb_pessoa(
    id number generated by default as identity,
    nome varchar2(100),
    telefone varchar2(50),
    cpf varchar2(50),
    nascimento date,
    primary key(id)
);

create table tb_endereco(
    logradouro varchar2(60),
    numero varchar2(15),
    complemento varchar2(20),
    bairro varchar2(40),
    municipio varchar2(50),
    cep varchar2(15),
    id_pessoa number,
    foreign key (id_pessoa) references tb_pessoa(id));